### ISSUE TITLE
Switch signature library from k256 to secp256k1

### ISSUE THREAD

**Issue by cryptoquick** [mikedilger/nostr-types#10]
I'd recommend switching from k256 to secp256k1 because the library using C bindings to the same library used by Bitcoin Core are much faster, is better maintained, and it still compiles to wasm, since we also use it in BDK and RGB. I discovered k256 was much slower when I went to try it out for the Rana Nostr vanity key generator. If you're curious and want to see for yourself the difference, try this branch:
https://github.com/grunch/rana/compare/main...cryptoquick:rana:perf-k256

**Comment by mikedilger** [comment]
I agree.

**Comment by mikedilger** [comment]
This is even more important now that I changed gossip-relay-picker to use the PublicKey directly (instead of the Hex version).

**Comment by mikedilger** [comment]
Done.  Used in gossip on the LMDB branch which will be stabilised and merged in pretty soon.

**Comment by cryptoquick** [comment]
Looking forward to seeing a potential performance improvement in gossip!

**Comment by mikedilger** [comment]
After I switched the performance got worse.  I had to stop serializing/deserializing from the SecretKey/PublicKey types directly because it was running crypto operations during the serialization (and I read/write to the data store constantly).  A recent comment changes my PublicKey type to `[u8; 32]`  so the ser/de is fast  and only converts to the secp256k1 type when it actually needs to do crypto.

Lots of recent work is speeding it up. This lib switch is a minor part of it.
